idf_component_register(
    SRCS
        "src/app_hls_player.c"
        "src/app_hls_player_ts_sync.c"
        "src/app_hls_player_http.c"
        "src/app_hls_player_audio.c"
        "src/app_hls_player_fetcher.c"
        "src/app_hls_player_log.c"
    INCLUDE_DIRS "include"
    PRIV_REQUIRES
        esp_common
        esp_http_client
        esp_https_ota
        iobewi_libs_m3u8_parser
        esp_audio_codec
        mbedtls
        esp_ringbuf
        esp_timer
)
